### ISSUE TITLE
Where is the file called scripts that many files import?

### ISSUE THREAD

**Issue by RossyYoung** [ycjungSubhuman/density-adaptation#2]

**Comment by ycjungSubhuman** [comment]
Dear RossyYoung.

It is in ext/large-steps. The module loaded into sys.path via this line. (https://github.com/ycjungSubhuman/density-adaptation/blob/d5688cc83a231e45dbeb255c794140c85f09ecc1/fitting_sphere.py#L18) 


Clone our repository using "git clone --recursive <URL>", or run "git submodule update --init --recursive" to download ext/large-steps .
